/*
 * generated by Xtext 2.30.0
 */
package dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTemperatureSensorValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(dsl.temperatureSensor.TemperatureSensorPackage.eINSTANCE);
		return result;
	}
}
