/*
 * generated by Xtext 2.30.0
 */
package dsl.parser.antlr;

import com.google.inject.Inject;
import dsl.parser.antlr.internal.InternalTemperatureSensorParser;
import dsl.services.TemperatureSensorGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TemperatureSensorParser extends AbstractAntlrParser {

	@Inject
	private TemperatureSensorGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTemperatureSensorParser createParser(XtextTokenStream stream) {
		return new InternalTemperatureSensorParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Device";
	}

	public TemperatureSensorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TemperatureSensorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
