/**
 * generated by Xtext 2.30.0
 */
package dsl.temperatureSensor;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Device</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dsl.temperatureSensor.Device#getName <em>Name</em>}</li>
 *   <li>{@link dsl.temperatureSensor.Device#getBatchSize <em>Batch Size</em>}</li>
 *   <li>{@link dsl.temperatureSensor.Device#getMaxSensor <em>Max Sensor</em>}</li>
 *   <li>{@link dsl.temperatureSensor.Device#getSampleRate <em>Sample Rate</em>}</li>
 * </ul>
 *
 * @see dsl.temperatureSensor.TemperatureSensorPackage#getDevice()
 * @model
 * @generated
 */
public interface Device extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see dsl.temperatureSensor.TemperatureSensorPackage#getDevice_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link dsl.temperatureSensor.Device#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Batch Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Batch Size</em>' containment reference.
   * @see #setBatchSize(Parameter)
   * @see dsl.temperatureSensor.TemperatureSensorPackage#getDevice_BatchSize()
   * @model containment="true"
   * @generated
   */
  Parameter getBatchSize();

  /**
   * Sets the value of the '{@link dsl.temperatureSensor.Device#getBatchSize <em>Batch Size</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Batch Size</em>' containment reference.
   * @see #getBatchSize()
   * @generated
   */
  void setBatchSize(Parameter value);

  /**
   * Returns the value of the '<em><b>Max Sensor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Sensor</em>' containment reference.
   * @see #setMaxSensor(Parameter)
   * @see dsl.temperatureSensor.TemperatureSensorPackage#getDevice_MaxSensor()
   * @model containment="true"
   * @generated
   */
  Parameter getMaxSensor();

  /**
   * Sets the value of the '{@link dsl.temperatureSensor.Device#getMaxSensor <em>Max Sensor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Sensor</em>' containment reference.
   * @see #getMaxSensor()
   * @generated
   */
  void setMaxSensor(Parameter value);

  /**
   * Returns the value of the '<em><b>Sample Rate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sample Rate</em>' containment reference.
   * @see #setSampleRate(Parameter)
   * @see dsl.temperatureSensor.TemperatureSensorPackage#getDevice_SampleRate()
   * @model containment="true"
   * @generated
   */
  Parameter getSampleRate();

  /**
   * Sets the value of the '{@link dsl.temperatureSensor.Device#getSampleRate <em>Sample Rate</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sample Rate</em>' containment reference.
   * @see #getSampleRate()
   * @generated
   */
  void setSampleRate(Parameter value);

} // Device
