/*
 * generated by Xtext 2.30.0
 */
package dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTemperatureSensorScopeProvider extends DelegatingScopeProvider {
}
