/*
 * generated by Xtext 2.30.0
 */
package dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import temperature_sensor.ui.internal.Temperature_sensorActivator;

public class TemperatureSensorUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Temperature_sensorActivator.getInstance().getInjector("dsl.TemperatureSensor");
	}

}
