/*
 * generated by Xtext 2.30.0
 */
package dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TemperatureSensorStandaloneSetup extends TemperatureSensorStandaloneSetupGenerated {

	public static void doSetup() {
		new TemperatureSensorStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
