/*
 * generated by Xtext 2.30.0
 */
package dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TemperatureSensorUiModule extends AbstractTemperatureSensorUiModule {

	public TemperatureSensorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
