/*
 * generated by Xtext 2.30.0
 */
package dsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import temperature_sensor.ui.internal.Temperature_sensorActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TemperatureSensorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Temperature_sensorActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Temperature_sensorActivator activator = Temperature_sensorActivator.getInstance();
		return activator != null ? activator.getInjector(Temperature_sensorActivator.DSL_TEMPERATURESENSOR) : null;
	}

}
