/*
 * generated by Xtext 2.30.0
 */
package dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dsl.TemperatureSensorRuntimeModule;
import dsl.TemperatureSensorStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TemperatureSensorIdeSetup extends TemperatureSensorStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TemperatureSensorRuntimeModule(), new TemperatureSensorIdeModule()));
	}
	
}
